steps:
  # Step 1: index.html-ah VM-kku copy panradhu
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'scp'
      - 'index.html'
      - 'sugi-instance:/var/www/html/index.html'
      - '--zone=us-central1-a'
      - '--quiet'

  # Step 2: Nginx server-ah restart panradhu
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'sugi-instance'
      - '--zone=us-central1-a'
      - '--command=sudo systemctl restart nginx'

options:
  logging: CLOUD_LOGGING_ONLY
