steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/Sugirtha2807/my-cicd-app']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - ssh
  - instance-name
  - --command= "cd project && git pull && npm install && npm start"
