options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - ssh
  - sugi-instance
  - --zone=us-central1-a
  - --command=cd ~ && rm -rf my-cicd-app && git clone https://github.com/sugirtha2807/my-cicd-app.git && sudo cp my-cicd-app/index.html /var/www/html/index.html
